[project]
name = "panasonic-miraie-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "fastmcp>=2.10.6",
    "paho-mqtt>=2.1.0",
]
